# Kustomize overlay for dev environment
# Combines Kustomize patches with Helm chart rendering.
# Requires --enable-helm in Argo CD ConfigMap (configured)

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-store-dev

helmCharts:
  - name: retail-store
    chartHome: ../../
    version: "1.0.0"
    releaseName: retail-store-dev
    namespace: retail-store-dev
    valuesFile: ../../values.yaml
    additionalValuesFiles:
      - ../../overlays/dev/values-dev.yaml
    includeCRDs: true

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: retail-store
      environment: dev

images:
  - name: ui
    newName: 758346258990.dkr.ecr.ap-southeast-1.amazonaws.com/uit-devsecops-dev-ui
    newTag: latest
  - name: cart
    newName: 758346258990.dkr.ecr.ap-southeast-1.amazonaws.com/uit-devsecops-dev-cart
    newTag: latest
  - name: orders
    newName: 758346258990.dkr.ecr.ap-southeast-1.amazonaws.com/uit-devsecops-dev-orders
    newTag: latest
  - name: catalog
    newName: 758346258990.dkr.ecr.ap-southeast-1.amazonaws.com/uit-devsecops-dev-catalog
    newTag: latest
  - name: checkout
    newName: 758346258990.dkr.ecr.ap-southeast-1.amazonaws.com/uit-devsecops-dev-checkout
    newTag: latest
