apiVersion: v1
kind: Service
metadata:
  name: dev-ui
spec:
  selector:
    app: ui
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dev-cart
spec:
  selector:
    app: cart
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dev-orders
spec:
  selector:
    app: orders
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dev-catalog
spec:
  selector:
    app: catalog
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dev-checkout
spec:
  selector:
    app: checkout
  ports:
    - port: 8080
      targetPort: 8080
