images:
  ui: 758346258990.dkr.ecr.ap-southeast-1.amazonaws.com/uit-devsecops-dev-ui
  cart: 758346258990.dkr.ecr.ap-southeast-1.amazonaws.com/uit-devsecops-dev-cart
  orders: 758346258990.dkr.ecr.ap-southeast-1.amazonaws.com/uit-devsecops-dev-orders
  catalog: 758346258990.dkr.ecr.ap-southeast-1.amazonaws.com/uit-devsecops-dev-catalog
  checkout: 758346258990.dkr.ecr.ap-southeast-1.amazonaws.com/uit-devsecops-dev-checkout
  tag: latest

ui:
  replicaCount: 2
  resources:
    requests: {memory: "128Mi", cpu: "100m"}
    limits: {memory: "256Mi", cpu: "250m"}

cart:
  replicaCount: 1
  resources:
    requests: {memory: "128Mi", cpu: "100m"}
    limits: {memory: "256Mi", cpu: "250m"}

orders:
  replicaCount: 1
  resources:
    requests: {memory: "128Mi", cpu: "100m"}
    limits: {memory: "256Mi", cpu: "250m"}

catalog:
  replicaCount: 1
  resources:
    requests: {memory: "64Mi", cpu: "50m"}
    limits: {memory: "128Mi", cpu: "150m"}

checkout:
  replicaCount: 1
  resources:
    requests: {memory: "128Mi", cpu: "100m"}
    limits: {memory: "256Mi", cpu: "250m"}
