apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-dev
  namespace: argocd
  labels:
    environment: dev
spec:
  project: retail-store
  source:
    repoURL: https://github.com/min-hit-1701/retail-store-gitops.git
    targetRevision: HEAD
    path: apps/retail-store/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
